dc:
	./doublecmd.sh

es:
	./es.sh

cyg:
	wget https://cygwin.com/setup-x86_64.exe
	mv setup-x86_64.exe ../bin/cygup.exe

clean:
	rm -rf doublecmd
	rm -f first.html
	rm -f second.html
	rm dc.zip
	rm es.zip
